using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CleTourism.Models;
using CleTourism.DAL;

namespace CleTourism.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            IActivityDAO dao = new ActivitySqlDAO(@"Data Source=.\SQLEXPRESS;Initial Catalog=CleTourism;Integrated Security=True");

            IList<Activity> activities = dao.GetAllActivities();

            return View(activities);
        }

        // TODO: need these actions? (were autogenerated on controller)

        //public IActionResult About()
        //{
        //    ViewData["Message"] = "Your application description page.";

        //    return View();
        //}

        //public IActionResult Contact()
        //{
        //    ViewData["Message"] = "Your contact page.";

        //    return View();
        //}

        //public IActionResult Privacy()
        //{
        //    return View();
        //}

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
    }
}
