using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CleTourism.Models;
using CleTourism.DAL;

namespace CleTourism.Controllers
{
    public class HomeController : Controller
    {
        private IActivityDAO activityDao;
        private INeighborhoodDAO neighborhoodDao;
        public HomeController(IActivityDAO activityDao, INeighborhoodDAO neighborhoodDao)
        {
            this.activityDao = activityDao;
            this.neighborhoodDao = neighborhoodDao;
        }

        public IActionResult Index()
        {
            IList<Activity> activities = activityDao.GetAllActivities();
            foreach (Activity activity in activities)
            {
                activity.NeighborhoodName = neighborhoodDao.GetNeighborhood(activity.Id).Name;
            }
            return View(activities);
        }

        public IActionResult ActivityDetails(int id)
        {
            Activity activity = activityDao.GetActivityDetails(id);
            activity.NeighborhoodName = neighborhoodDao.GetNeighborhood(id).Name;

            return View(activity);
        }

        // TODO: need these actions? (were autogenerated on controller)

        //public IActionResult About()
        //{
        //    ViewData["Message"] = "Your application description page.";

        //    return View();
        //}

        //public IActionResult Contact()
        //{
        //    ViewData["Message"] = "Your contact page.";

        //    return View();
        //}

        //public IActionResult Privacy()
        //{
        //    return View();
        //}

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
    }
}
